from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

from vibeguard import __version__
from vibeguard.ui.banner import print_banner
from vibeguard.ui.quickstart import print_quick_start

import typer
from rich.console import Console
from rich.table import Table

from vibeguard.core.builders import build_context, build_next_prompt, build_pack, build_plan, build_prompt
from vibeguard.core.diff_analyzer import analyze_diff
from vibeguard.core.report_generator import (
    ensure_vibeguard_dir,
    render_diff_report,
    render_risk_report,
    render_verification_report,
    write_text,
)
from vibeguard.core.risk_engine import Risk, analyze_risks
from vibeguard.core.scanner import scan_project
from vibeguard.core.token_packer import pack_files
from vibeguard.core.verifier import verify_project
from vibeguard.llm import (
    DEFAULT_MAX_TOKENS,
    DEFAULT_NVIDIA_MODEL,
    LLMConfigurationError,
    LLMRequestError,
    enhance_coding_prompt,
)
from vibeguard.utils.os_utils import get_os_name


def display_path(path: Path) -> str:
    return str(path)


def safe_path(p: Path | str) -> Path:
    p_str = str(p)
    if "\\" in p_str:
        p_str = p_str.replace("\\", "/")
    return Path(p_str)


app = typer.Typer(
    name="vibeguard",
    help="Guardrails for vibe-coded software.",
    no_args_is_help=False,
)
console = Console()


def version_callback(value: bool) -> None:
    if value:
        console.print(f"VibeGuard {__version__}")
        raise typer.Exit()


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    version: bool = typer.Option(
        None,
        "--version",
        "-V",
        callback=version_callback,
        is_eager=True,
        help="Show VibeGuard version and exit.",
    ),
) -> None:
    if ctx.invoked_subcommand is None:
        print_banner(console, compact=False)
        print_quick_start(console)


@app.command()
def init(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Initialize .vibeguard in a project."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=False, project=project)
    out = ensure_vibeguard_dir(project)
    config = out / "config.yaml"
    if not config.exists():
        config.write_text(_default_config(project), encoding="utf-8")
    for name in ("context.md", "prompt.md", "task.md", "pack.md"):
        path = out / name
        if not path.exists():
            path.write_text(f"# {name}\n\nGenerated by VibeGuard.\n", encoding="utf-8")
    console.print("VibeGuard initialized successfully.")
    console.print(f"Created {display_path(config)}")


@app.command()
def scan(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Scan project structure, stack, important files, and ignored folders."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    result = scan_project(project)
    _write_scan_cache(project, result)
    console.print(f"Project type: {result.detection.primary_type}")
    console.print(f"Package manager: {result.detection.package_manager or 'Unknown'}")
    console.print(f"Frameworks: {', '.join(result.detection.frameworks) or 'None detected'}")
    table = Table(title="Detected important files")
    table.add_column("File")
    for file in result.important_files[:30]:
        table.add_row(file)
    console.print(table)
    if result.ignored:
        console.print("Ignored: " + ", ".join(result.ignored))


@app.command()
def context(
    goal_arg: str = typer.Argument(None, help="Goal for the AI coding task."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal for the AI coding task."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    max_tokens: int = typer.Option(8000, "--max-tokens", "-t", help="Context token budget."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Create an AI-readable context pack."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    scan_result = scan_project(project)
    pack_result = pack_files(project, scan_result, resolved_goal, max_tokens)
    path = write_text(project, "context.md", build_context(scan_result, resolved_goal, pack_result))
    console.print(f"Context written: {display_path(path)}")


@app.command()
def plan(
    goal_arg: str = typer.Argument(None, help="Goal for the AI coding task."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal for the AI coding task."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Turn a rough idea into a guarded implementation plan."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    scan_result = scan_project(project)
    path = write_text(project, "task.md", build_plan(scan_result, resolved_goal))
    console.print(f"Plan written: {display_path(path)}")


@app.command()
def prompt(
    goal_arg: str = typer.Argument(None, help="Goal for the AI coding task."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal for the AI coding task."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    max_tokens: int = typer.Option(8000, "--max-tokens", "-t", help="Prompt file budget."),
    use_llm: bool = typer.Option(
        False,
        "--llm",
        help="Refine the generated prompt with NVIDIA GLM-5.2 (requires NVIDIA_API_KEY).",
    ),
    model: str = typer.Option(DEFAULT_NVIDIA_MODEL, "--model", help="NVIDIA NIM model name."),
    llm_max_tokens: int = typer.Option(
        DEFAULT_MAX_TOKENS,
        "--llm-max-tokens",
        min=1,
        help="Maximum tokens requested from the optional LLM.",
    ),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Generate a high-quality prompt for AI coding tools."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    scan_result = scan_project(project)
    pack_result = pack_files(project, scan_result, resolved_goal, max_tokens)
    prompt_content = build_prompt(scan_result, resolved_goal, pack_result)
    if use_llm:
        console.print(f"Refining prompt with NVIDIA model: {model}")
        try:
            prompt_content = enhance_coding_prompt(
                prompt_content,
                model=model,
                max_tokens=llm_max_tokens,
            )
        except (LLMConfigurationError, LLMRequestError) as exc:
            console.print(f"ERROR: {exc}")
            raise typer.Exit(1) from exc
    path = write_text(project, "prompt.md", prompt_content)
    console.print(f"Prompt written: {display_path(path)}")


@app.command()
def pack(
    goal_arg: str = typer.Argument(None, help="Goal used for relevance scoring."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal used for relevance scoring."),
    max_tokens: int = typer.Option(8000, "--max-tokens", "-t", help="Maximum estimated token budget."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Create a token-aware context pack."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    scan_result = scan_project(project)
    result = pack_files(project, scan_result, resolved_goal, max_tokens)
    path = write_text(project, "pack.md", build_pack(scan_result, resolved_goal, result, max_tokens))
    console.print(f"Pack written: {display_path(path)}")
    console.print(f"Estimated tokens: {result.estimated_tokens} / {max_tokens}")
    console.print("Included files:")
    for item in result.included:
        console.print(f"- {item.path}")
    console.print("Excluded files:")
    excluded_paths = [item.path for item in result.excluded[:20]] or ["node_modules", ".git", ".vibeguard", "assets", "dist", "build"]
    for excluded in excluded_paths:
        console.print(f"- {excluded}")


@app.command()
def verify(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Run available verification checks without installing tools."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    scan_result = scan_project(project)
    if scan_result.detection.package_manager in ("yarn", "pnpm", "bun"):
        console.print(f"WARNING: Detected {scan_result.detection.package_manager} project. Automatic verification currently supports npm in MVP.")
    report = verify_project(project, scan_result.detection)
    path = write_text(project, "reports/verification_report.md", render_verification_report(report, scan_result.detection.primary_type, scan_result.detection.package_manager or "Unknown"))
    console.print("Verification Report")
    for check in report.checks:
        if check.status == "Passed":
            console.print(f"OK {check.name}")
        elif check.status == "Skipped":
            console.print(f"WARNING {check.name} skipped: {check.details}")
        else:
            console.print(f"FAILED {check.name}: {check.details[:160]}")
    console.print(f"Report written: {display_path(path)}")


@app.command()
def doctor(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Check whether VibeGuard can run cleanly in the project."""
    root = safe_path(project).resolve()
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=False, project=root)
    scan_result = scan_project(root)
    detection = scan_result.detection
    warnings = 0
    failures = 0

    os_name = get_os_name().title()
    python_ver = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    cwd = Path.cwd()
    project_path = root

    vibeguard_avail = "available" if shutil.which("vibeguard") else "missing"
    vbg_avail = "available" if shutil.which("vbg") else "missing"
    vg_path = shutil.which("vg")
    try:
        import vibeguard
        module_path = Path(vibeguard.__file__).resolve()
        if "site-packages" in str(module_path) or "dist-packages" in str(module_path):
            install_mode = "installed"
        else:
            install_mode = "editable"
    except Exception:
        install_mode = "unknown"

    git_avail = "available" if shutil.which("git") else "missing"
    node_avail = "available" if shutil.which("node") else "missing"
    npm_avail = "available" if shutil.which("npm") else "missing"
    python_exec = sys.executable
    pytest_avail = "available" if shutil.which("pytest") else "missing"
    ruff_avail = "available" if shutil.which("ruff") else "missing"
    nvidia_llm = "configured" if os.getenv("NVIDIA_API_KEY") else "missing (optional)"

    git_repo = "detected" if _has_git_repository(root) else "missing"
    pkg_json = "detected" if (root / "package.json").exists() else "missing"
    tsconfig = "detected" if (root / "tsconfig.json").exists() else "missing"
    vibeguard_folder = "detected" if (root / ".vibeguard").exists() else "missing"
    reports_folder = "detected" if (root / ".vibeguard" / "reports").exists() else "missing"

    console.print("VibeGuard Doctor")
    console.print("")
    console.print("System:")
    console.print(f"- OS: {os_name}")
    console.print(f"- Python: {python_ver}")
    console.print(f"- Current working directory: {display_path(cwd)}")
    console.print(f"- Project path: {display_path(project_path)}")
    console.print("")
    console.print("CLI:")
    console.print(f"- vibeguard command: {vibeguard_avail}")
    console.print(f"- vbg command: {vbg_avail}")
    console.print(f"- Python executable: {display_path(Path(python_exec))}")
    console.print(f"- Package install mode: {install_mode}")
    console.print("")
    console.print("Tools:")
    console.print(f"- Git: {git_avail}")
    console.print(f"- Node: {node_avail}")
    console.print(f"- npm: {npm_avail}")
    console.print(f"- Python executable: {display_path(Path(python_exec))}")
    console.print(f"- pytest: {pytest_avail}")
    console.print(f"- ruff: {ruff_avail}")
    console.print(f"- NVIDIA LLM: {nvidia_llm}")
    console.print("")
    console.print("Project:")
    console.print(f"- Git repository: {git_repo}")
    console.print(f"- package.json: {pkg_json}")
    console.print(f"- tsconfig.json: {tsconfig}")
    console.print(f"- .vibeguard folder: {vibeguard_folder}")
    console.print(f"- reports folder: {reports_folder}")
    console.print(f"- Project type: {detection.primary_type}")
    console.print(f"- Package manager: {detection.package_manager or 'None'}")
    console.print("")
    console.print("Security:")
    console.print("- Sensitive files ignored: Yes")
    console.print("- Symlink traversal disabled: Yes")
    console.print("- Shell execution disabled: Yes")
    console.print("- Secret redaction enabled: Yes")
    console.print("")
    console.print("--------------------------------------------------")
    console.print("")

    if get_os_name() in ("windows", "macos", "linux"):
        console.print(f"OK OS detected: {os_name}")
    else:
        console.print(f"WARNING OS detected: {os_name}")
        warnings += 1

    console.print(f"OK Python detected: {python_ver}")

    if vibeguard_avail == "available":
        console.print("OK vibeguard command available")
    else:
        console.print("WARNING vibeguard command not found in PATH")
        console.print("Suggestion: run `pip install -e .` or use `pipx install -e .` in your workspace.")
        warnings += 1

    if vbg_avail == "available":
        console.print("OK vbg command available")
    else:
        console.print("WARNING vbg command not found in PATH")
        warnings += 1

    if get_os_name() == "linux" and vg_path:
        console.print("WARNING: Linux already provides a system command named 'vg'. Use 'vbg' instead.")

    if git_avail == "available":
        console.print("OK Git available")
    else:
        console.print("WARNING Git missing")
        warnings += 1

    if npm_avail == "available":
        console.print("OK npm available")
    else:
        console.print("WARNING npm missing")
        warnings += 1

    failures += _doctor_required("Git repository detected", git_repo == "detected")
    failures += _doctor_required("package.json detected", pkg_json == "detected")
    warnings += _doctor_warning("TypeScript project detected", tsconfig == "detected")
    warnings += _doctor_warning(".vibeguard folder detected", vibeguard_folder == "detected")
    warnings += _doctor_warning("reports folder detected", reports_folder == "detected")

    if detection.primary_type != "Unknown":
        console.print(f"OK Project type detected: {detection.primary_type}")
    else:
        console.print("WARNING project type not detected")
        warnings += 1

    if detection.package_manager:
        console.print(f"OK Package manager detected: {detection.package_manager}")
    else:
        console.print("WARNING package manager not detected")
        warnings += 1

    for script in ("test", "lint", "typecheck"):
        if script in detection.scripts:
            console.print(f"OK {script} script available")
        else:
            console.print(f"WARNING {script} script missing")
            warnings += 1

    console.print("OK secret redaction enabled")
    console.print("OK shell execution disabled")

    console.print("")
    if failures:
        console.print("Status: Not ready")
    elif warnings:
        console.print("Status: Ready with warnings")
    else:
        console.print("Status: Ready")


@app.command("all")
def run_all(
    goal_arg: str = typer.Argument(None, help="Goal for the full VibeGuard workflow."),
    goal: str = typer.Option(None, "--goal", "-g", help="Goal for the full VibeGuard workflow."),
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    max_tokens: int = typer.Option(8000, "--max-tokens", "-t", help="Maximum estimated token budget."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Run the complete MVP workflow."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=False, project=project)
    resolved_goal = goal or goal_arg
    if not resolved_goal:
        console.print("ERROR: Missing option '--goal' / '-g' or positional argument.")
        raise typer.Exit(1)
    console.print("Running VibeGuard workflow...")
    console.print("")
    if not project.exists():
        console.print(f"ERROR: Project path '{display_path(project)}' does not exist.")
        raise typer.Exit(1)

    try:
        ensure_vibeguard_dir(project)
    except PermissionError:
        console.print("ERROR: Permission denied. Cannot create .vibeguard folder.")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"ERROR: Cannot create .vibeguard folder. Reason: {e}")
        raise typer.Exit(1)

    scan_result = scan_project(project)
    if scan_result.detection.package_manager in ("yarn", "pnpm", "bun"):
        console.print(f"WARNING: Detected {scan_result.detection.package_manager} project. Automatic verification currently supports npm in MVP.")
    _write_scan_cache(project, scan_result)
    console.print("OK scan completed")

    context_pack = pack_files(project, scan_result, resolved_goal, max_tokens)
    write_text(project, "context.md", build_context(scan_result, resolved_goal, context_pack))
    console.print("OK context generated")

    write_text(project, "task.md", build_plan(scan_result, resolved_goal))
    console.print("OK plan generated")

    prompt_pack = pack_files(project, scan_result, resolved_goal, max_tokens)
    write_text(project, "prompt.md", build_prompt(scan_result, resolved_goal, prompt_pack))
    console.print("OK prompt generated")

    pack_result = pack_files(project, scan_result, resolved_goal, max_tokens)
    write_text(project, "pack.md", build_pack(scan_result, resolved_goal, pack_result, max_tokens))
    console.print("OK pack generated")

    verification = verify_project(project, scan_result.detection)
    write_text(project, "reports/verification_report.md", render_verification_report(verification, scan_result.detection.primary_type, scan_result.detection.package_manager or "Unknown"))
    if any(c.status == "Failed" for c in verification.checks):
        console.print("WARNING verify completed with failed checks")
    elif any(c.status == "Skipped" for c in verification.checks):
        console.print("WARNING verify completed with skipped checks")
    else:
        console.print("OK verification completed")

    diff = analyze_diff(project)
    if diff.status != "ok":
        if diff.status == "git_missing":
            console.print("WARNING Git not available. Skipping diff analysis.")
        elif diff.status == "not_git_repo":
            console.print("WARNING No Git repository detected. Skipping diff analysis.")
        elif diff.status == "no_commits":
            console.print("WARNING Git repository has no baseline commit. Skipping diff analysis.")
    else:
        write_text(project, "reports/diff_report.md", render_diff_report(diff))
        console.print("OK diff report generated")

        risk_report = analyze_risks(diff)
        write_text(project, "reports/risk_report.md", render_risk_report(risk_report))
        if any(r.severity in ("MEDIUM", "HIGH") for r in risk_report.risks):
            console.print("WARNING risk report generated with medium/high findings")
        else:
            console.print("OK risk report generated")

        risk_lines = [f"{risk.severity} {risk.path + ': ' if risk.path else ''}{risk.message}" for risk in risk_report.risks]
        write_text(project, "reports/next_prompt.md", build_next_prompt(risk_lines))
        console.print("OK next prompt generated")

    console.print("")
    console.print("Workflow complete.")
    console.print("Reports written to .vibeguard/reports")


@app.command("diff-explain")
def diff_explain(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Explain uncommitted Git changes."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    diff = analyze_diff(project)
    if diff.status == "git_missing":
        console.print("Git not available. Skipping diff analysis.")
        return
    elif diff.status == "not_git_repo":
        console.print("No Git repository detected. Run `git init` to enable diff analysis.")
        return
    elif diff.status == "no_commits":
        console.print("Git repository has no baseline commit. Create an initial commit to enable meaningful diff analysis.")
        return

    path = write_text(project, "reports/diff_report.md", render_diff_report(diff))
    if not diff.changed_files:
        console.print("No uncommitted Git diff detected.")
    else:
        console.print("Changed files:")
        for changed in diff.changed_files:
            console.print(f"- {changed.path}")
        risk_notes = _diff_risk_notes([changed.path for changed in diff.changed_files])
        if risk_notes:
            console.print("Risk:")
            for note in risk_notes:
                console.print(f"- {note}")
    console.print(f"Report written: {display_path(path)}")


@app.command()
def risks(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Show risky patterns in the current Git diff."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    diff = analyze_diff(project)
    if diff.status == "git_missing":
        console.print("Git not available. Skipping diff analysis.")
        return
    elif diff.status == "not_git_repo":
        console.print("No Git repository detected. Run `git init` to enable diff analysis.")
        return
    elif diff.status == "no_commits":
        console.print("Git repository has no baseline commit. Create an initial commit to enable meaningful diff analysis.")
        return

    report = analyze_risks(diff)
    path = write_text(project, "reports/risk_report.md", render_risk_report(report))
    console.print(f"Risk Level: {report.overall.title()}")
    for risk in report.risks:
        console.print(f"WARNING {risk.message}")
        if risk.path:
            console.print(f"File: {risk.path}")
        console.print(f"Reason: {_risk_reason(risk)}")
    console.print(f"Report written: {display_path(path)}")


@app.command("next-prompt")
def next_prompt(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    no_banner: bool = typer.Option(False, "--no-banner", help="Disable the startup banner."),
) -> None:
    """Generate the next best prompt after reviewing risky changes."""
    project = safe_path(project)
    if no_banner:
        os.environ["VIBEGUARD_NO_BANNER"] = "1"
    print_banner(console, compact=True, project=project)
    diff = analyze_diff(project)
    if diff.status == "git_missing":
        console.print("Git not available. Skipping diff analysis.")
        return
    elif diff.status == "not_git_repo":
        console.print("No Git repository detected. Run `git init` to enable diff analysis.")
        return
    elif diff.status == "no_commits":
        console.print("Git repository has no baseline commit. Create an initial commit to enable meaningful diff analysis.")
        return

    report = analyze_risks(diff)
    risk_lines = [f"{risk.severity} {risk.path + ': ' if risk.path else ''}{risk.message}" for risk in report.risks]
    path = write_text(project, "reports/next_prompt.md", build_next_prompt(risk_lines))
    console.print(f"Next prompt written: {display_path(path)}")


def _doctor_required(label: str, ok: bool) -> int:
    if ok:
        console.print(f"OK {label}")
        return 0
    console.print(f"FAILED {label}")
    return 1


def _doctor_warning(label: str, ok: bool) -> int:
    if ok:
        console.print(f"OK {label}")
        return 0
    console.print(f"WARNING {label}")
    return 1


def _has_git_repository(root: Path) -> bool:
    if (root / ".git").exists():
        return True
    try:
        result = subprocess.run(["git", "rev-parse", "--is-inside-work-tree"], cwd=root, text=True, capture_output=True, check=False)
    except FileNotFoundError:
        return False
    return result.returncode == 0 and result.stdout.strip() == "true"


def _diff_risk_notes(paths: list[str]) -> list[str]:
    lower_paths = [path.lower() for path in paths]
    notes: list[str] = []
    if any("auth" in path for path in lower_paths):
        notes.append("Auth-related file changed")
    if paths and not any(any(term in path for term in (".test.", ".spec.", "__tests__", "/tests/", "\\tests\\")) for path in lower_paths):
        notes.append("No test file changed")
    return notes


def _risk_reason(risk: Risk) -> str:
    lower = risk.message.lower()
    if "auth" in lower:
        return "auth-related files require manual review"
    if "no test" in lower:
        return "feature code changed without test update"
    if "secret" in lower:
        return "changed code contains possible hardcoded secret/API key/token"
    if "dependency" in lower or "lockfile" in lower:
        return "dependency changes can affect runtime and supply-chain safety"
    if "deleted" in lower:
        return "deleted files may break imports or behavior"
    if "large" in lower:
        return "large diffs are harder to review and may include unrelated edits"
    return risk.message.rstrip(".")


def _write_scan_cache(project: Path, result) -> None:
    out = ensure_vibeguard_dir(project)
    data = {
        "type": result.detection.primary_type,
        "languages": result.detection.languages,
        "frameworks": result.detection.frameworks,
        "files": result.files,
        "important_files": result.important_files,
        "ignored": result.ignored,
    }
    (out / "cache" / "scan.json").write_text(json.dumps(data, indent=2), encoding="utf-8")


def _default_config(project: Path) -> str:
    name = Path(project).resolve().name
    return f'''project_name: "{name}"
ignore:
  - node_modules
  - .git
  - dist
  - build
  - .next
  - venv
  - __pycache__
protected_files:
  - ".env"
  - ".env.production"
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "migrations/**"
risky_paths:
  - auth
  - payment
  - billing
  - security
  - middleware
  - permissions
  - admin
  - database
  - migrations
verification:
  python:
    - "python -m compileall ."
    - "pytest"
    - "ruff check ."
  node:
    - "npm test"
    - "npm run lint"
    - "npm run typecheck"
token_budget:
  default_max_tokens: 8000
'''


if __name__ == "__main__":
    app()
